version: '3.8'
services:
  springboot-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/imagesdb

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
